name: project1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1 #edited

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  get: ^4.6.5
  get_storage: ^2.1.1
  search_page: ^2.3.0
  http: ^0.13.5
  flutter_rating_bar: ^4.0.1
  simple_speed_dial: ^0.1.7
  otp_text_field: ^1.1.3
  email_otp: ^2.0.1
  timer_count_down: ^2.2.2
  flutter_spinkit: ^5.1.0
  intl_phone_field: ^3.1.0
  pusher_client: ^2.0.0
  fluttertoast: ^8.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
   - assets/images/

  fonts:
  - family: KufiArabic
    fonts:
      - asset: assets/fonts/NotoKufiArabic-VariableFont_wght.ttf
  - family: defaultEnglish
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf

